# SPDX-License-Identifier: MIT
"""
clawmeets/integrations/media/_lib.py

Provider-agnostic media generation — image, audio (TTS), and video — backed by
direct REST calls (httpx) to the selected provider. Supersedes the old
``image_gen`` integration.

Every entry function resolves its settings with the order
``flag > config-file section > env var > built-in default`` so an agent can run
fully from flags (ad-hoc), fully from the per-agent config
(``$CLAWMEETS_AGENT_DIR/skill-hub/configs/media.json``, one section per
modality), or any mix. Generated bytes are written atomically under the
resolved ``output_dir`` and the absolute path is returned so consumers pick it
up by path (e.g. ``update_file`` to surface it in chat).

Why not the LLM provider layer (opencode / openrouter)? ``LLMProvider.invoke``
returns text + token usage only — any returned media would be discarded. Media
generation lives here, in a direct-httpx skill. openrouter / opencode can still
be selected as a ``provider`` value wherever their REST endpoints return media.
"""
from __future__ import annotations

import base64
import hashlib
import io
import json
import logging
import mimetypes
import os
import time
import wave
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from clawmeets.integrations._config_resolve import resolve_skill_config_path

logger = logging.getLogger(__name__)

MODALITIES = ("image", "audio", "video")

PROVIDERS: dict[str, set[str]] = {
    "image": {"openai", "gemini", "nano-banana"},
    "audio": {"openai", "elevenlabs", "gemini"},
    "video": {"replicate", "fal"},
}

# Providers that support image-conditioned editing/compositing (the
# ``--input-image`` path). Imagen (``gemini``) has no simple edit endpoint here.
IMAGE_EDIT_PROVIDERS = {"openai", "nano-banana"}

DEFAULT_PROVIDER = {"image": "openai", "audio": "openai", "video": "replicate"}

DEFAULT_MODELS: dict[tuple[str, str], str] = {
    ("image", "openai"):      "gpt-image-2",
    ("image", "gemini"):      "imagen-3.0-generate-002",
    ("image", "nano-banana"): "gemini-2.5-flash-image",
    ("audio", "openai"):      "gpt-4o-mini-tts",
    ("audio", "elevenlabs"):  "eleven_multilingual_v2",
    ("audio", "gemini"):      "gemini-2.5-flash-preview-tts",
    ("video", "replicate"):   "",   # caller must pass --model (owner/name slug)
    ("video", "fal"):         "",   # caller must pass --model (fal-ai/... slug)
}

# Which env var holds each provider's key (the env fallback when neither a
# --api-key flag nor a config `api_key` is set).
PROVIDER_ENV = {
    "openai":      "OPENAI_API_KEY",
    "gemini":      "GEMINI_API_KEY",
    "nano-banana": "GEMINI_API_KEY",
    "elevenlabs":  "ELEVENLABS_API_KEY",
    "replicate":   "REPLICATE_API_TOKEN",
    "fal":         "FAL_KEY",
}

DEFAULT_TIMEOUTS = {"image": 120.0, "audio": 120.0, "video": 900.0}

OPENAI_IMAGES_URL = "https://api.openai.com/v1/images/generations"
OPENAI_IMAGE_EDITS_URL = "https://api.openai.com/v1/images/edits"
OPENAI_SPEECH_URL = "https://api.openai.com/v1/audio/speech"
GEMINI_BASE_URL   = "https://generativelanguage.googleapis.com/v1beta/models"
ELEVENLABS_BASE   = "https://api.elevenlabs.io/v1/text-to-speech"
REPLICATE_BASE    = "https://api.replicate.com/v1"
FAL_QUEUE_BASE    = "https://queue.fal.run"

# gpt-image-2 keeps the gpt-image-1 sizes and adds a 2K tier (2x each aspect).
OPENAI_SIZES     = {
    "1024x1024", "1024x1536", "1536x1024",
    "2048x2048", "2048x3072", "3072x2048",
    "auto",
}
OPENAI_QUALITIES = {"auto", "low", "medium", "high"}
GEMINI_ASPECTS   = {"1:1", "9:16", "16:9", "3:4", "4:3"}

ELEVENLABS_DEFAULT_VOICE = "21m00Tcm4TlvDq8ikWAM"  # "Rachel"


# --------------------------------------------------------------------------- #
# Shared helpers
# --------------------------------------------------------------------------- #
def _resolve_env(value: Any) -> Any:
    if not isinstance(value, str):
        return value
    if "${" not in value:
        return value
    out = value
    for key, val in os.environ.items():
        out = out.replace(f"${{{key}}}", val)
    return out


def _slug(text: str, max_len: int = 32) -> str:
    out = []
    last_dash = False
    for ch in text.lower():
        if ch.isalnum():
            out.append(ch)
            last_dash = False
        elif not last_dash:
            out.append("-")
            last_dash = True
    s = "".join(out).strip("-")
    return (s[:max_len] or "media").rstrip("-")


def _atomic_write_bytes(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + f".tmp.{os.getpid()}.{int(time.time() * 1000)}")
    tmp.write_bytes(data)
    tmp.replace(path)


def _err_msg(resp: Any) -> str:
    try:
        j = resp.json()
        if isinstance(j, dict):
            err = j.get("error")
            if isinstance(err, dict):
                return err.get("message") or resp.text
            if isinstance(err, str):
                return err
            return j.get("detail") or resp.text
    except Exception:
        pass
    return resp.text


def _data_uri(image_path: str) -> str:
    p = Path(image_path).expanduser()
    if not p.exists():
        raise RuntimeError(f"--input-image not found: {p}")
    mime, _ = mimetypes.guess_type(str(p))
    mime = mime or "image/png"
    b64 = base64.b64encode(p.read_bytes()).decode("ascii")
    return f"data:{mime};base64,{b64}"


def _load_input_image(path: str) -> tuple[bytes, str, str]:
    """Read a local image into ``(raw_bytes, mime, filename)``.

    Raises ``RuntimeError`` if the path is missing or resolves to a non-image
    mime type. Shared by both image-edit backends.
    """
    p = Path(path).expanduser()
    if not p.exists():
        raise RuntimeError(f"--input-image not found: {p}")
    mime, _ = mimetypes.guess_type(str(p))
    mime = mime or "image/png"
    if not mime.startswith("image/"):
        raise RuntimeError(
            f"--input-image {p} is not an image (guessed mime {mime!r}); "
            "pass a PNG/JPEG/WebP file.")
    return p.read_bytes(), mime, p.name


def _pcm_to_wav(pcm: bytes, rate: int, channels: int = 1, sampwidth: int = 2) -> bytes:
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        w.setnchannels(channels)
        w.setsampwidth(sampwidth)
        w.setframerate(rate)
        w.writeframes(pcm)
    return buf.getvalue()


def _ext_from_url(url: str, fallback: str) -> str:
    path = url.split("?", 1)[0]
    dot = path.rsplit(".", 1)
    if len(dot) == 2 and 1 <= len(dot[1]) <= 5 and dot[1].isalnum():
        return dot[1].lower()
    return fallback


def _maybe_number(value: str) -> Any:
    try:
        if "." in value:
            return float(value)
        return int(value)
    except (TypeError, ValueError):
        return value


# --------------------------------------------------------------------------- #
# Config resolution: flag > config-file section > env > default
# --------------------------------------------------------------------------- #
def load_config(modality: str, config_file: str, overrides: dict) -> dict:
    """Resolve the effective settings for one modality.

    ``overrides`` are CLI flag values; only non-empty ones take effect. Missing
    config file is fine — flags + env can fully supply the settings. Raises
    ``RuntimeError`` on an unsupported provider, a missing api_key, or an
    unresolvable output_dir.
    """
    if modality not in MODALITIES:
        raise RuntimeError(f"unknown modality {modality!r}; choose one of {MODALITIES}")

    section: dict = {}
    path = resolve_skill_config_path("media", config_file)
    if path:
        p = Path(path).expanduser()
        if p.exists():
            raw = p.read_text()
            try:
                from clawmeets.utils.jsonc import parse_jsonc
                full = parse_jsonc(raw)
            except Exception:
                full = json.loads(raw)
            if not isinstance(full, dict):
                raise RuntimeError(
                    f"media config must be a JSON object, got {type(full).__name__}"
                )
            sec = full.get(modality)
            if isinstance(sec, dict):
                section = sec

    merged = dict(section)
    for key, val in overrides.items():
        if val not in (None, ""):
            merged[key] = val

    provider = (merged.get("provider") or DEFAULT_PROVIDER[modality]).strip()
    if provider not in PROVIDERS[modality]:
        raise RuntimeError(
            f"media {modality}: `provider` {provider!r} is not supported; "
            f"choose one of: {sorted(PROVIDERS[modality])}"
        )

    api_key = _resolve_env(merged.get("api_key"))
    if not isinstance(api_key, str) or not api_key or api_key.startswith("${"):
        env_name = PROVIDER_ENV.get(provider, "")
        api_key = os.environ.get(env_name, "") if env_name else ""
    if not api_key:
        env_name = PROVIDER_ENV.get(provider, "<provider key>")
        raise RuntimeError(
            f"media {modality}: no api_key for provider {provider!r}. Pass "
            f"--api-key, set `api_key` in the media config, or export "
            f"{env_name} on the runner before `clawmeets start`."
        )

    output_dir_raw = _resolve_env(merged.get("output_dir") or "")
    if not isinstance(output_dir_raw, str) or not output_dir_raw or "${" in output_dir_raw:
        agent_dir = os.environ.get("CLAWMEETS_AGENT_DIR", "")
        if agent_dir:
            output_dir_raw = str(Path(agent_dir) / "media" / modality)
        else:
            raise RuntimeError(
                f"media {modality}: `output_dir` is unset/unresolved and "
                "CLAWMEETS_AGENT_DIR is not in the env. Pass --output-dir or set "
                "output_dir in the config."
            )
    output_dir = Path(output_dir_raw).expanduser()

    return {
        "modality": modality,
        "provider": provider,
        "api_key": api_key,
        "model": (merged.get("model") or DEFAULT_MODELS[(modality, provider)]).strip(),
        "output_dir": output_dir,
        "timeout_seconds": float(merged.get("timeout_seconds") or DEFAULT_TIMEOUTS[modality]),
        "poll_interval_seconds": float(merged.get("poll_interval_seconds") or 5),
        # modality-specific defaults pulled from the config section
        "default_size": merged.get("default_size") or "",
        "default_quality": merged.get("default_quality") or "",
        "voice": merged.get("voice") or "",
        "audio_format": merged.get("audio_format") or merged.get("format") or "",
    }


def _finalize(cfg: dict, prompt: str, data: bytes, ext: str, extra: dict) -> dict:
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    digest = hashlib.sha256(prompt.encode("utf-8")).hexdigest()[:8]
    filename = f"{ts}-{_slug(prompt)}-{digest}.{ext}"
    out_path = (cfg["output_dir"] / filename).resolve()
    _atomic_write_bytes(out_path, data)
    result = {
        "media_path": str(out_path),
        f"{cfg['modality']}_path": str(out_path),
        "media_type": cfg["modality"],
        "prompt_used": prompt,
        "provider": cfg["provider"],
        "model": cfg["model"],
        "generated_at": ts,
    }
    result.update(extra)
    return result


# --------------------------------------------------------------------------- #
# Image backends
# --------------------------------------------------------------------------- #
def _image_openai(cfg: dict, prompt: str, size: str, quality: str) -> bytes:
    import httpx

    body = {"model": cfg["model"], "prompt": prompt, "size": size, "quality": quality, "n": 1}
    headers = {"Authorization": f"Bearer {cfg['api_key']}", "Content-Type": "application/json"}
    with httpx.Client(timeout=cfg["timeout_seconds"]) as client:
        resp = client.post(OPENAI_IMAGES_URL, json=body, headers=headers)
    if resp.status_code >= 400:
        raise RuntimeError(f"OpenAI Images API returned {resp.status_code}: {_err_msg(resp)}")
    data = (resp.json().get("data") or [])
    if not data:
        raise RuntimeError(f"OpenAI Images API returned no data: {resp.json()!r}")
    b64 = data[0].get("b64_json")
    if not b64:
        raise RuntimeError("OpenAI Images API response missing `b64_json`; check `model`.")
    return base64.b64decode(b64)


def _image_gemini(cfg: dict, prompt: str, aspect: str) -> bytes:
    import httpx

    url = f"{GEMINI_BASE_URL}/{cfg['model']}:predict"
    body = {"instances": [{"prompt": prompt}], "parameters": {"sampleCount": 1, "aspectRatio": aspect}}
    with httpx.Client(timeout=cfg["timeout_seconds"]) as client:
        resp = client.post(url, params={"key": cfg["api_key"]}, json=body,
                           headers={"Content-Type": "application/json"})
    if resp.status_code >= 400:
        raise RuntimeError(f"Gemini Imagen API returned {resp.status_code}: {_err_msg(resp)}")
    preds = (resp.json().get("predictions") or [])
    if not preds:
        raise RuntimeError(f"Gemini Imagen API returned no predictions: {resp.json()!r}")
    b64 = preds[0].get("bytesBase64Encoded")
    if not b64:
        raise RuntimeError(
            f"Gemini Imagen response missing image bytes; likely a safety filter "
            f"rejection. Full prediction: {preds[0]!r}"
        )
    return base64.b64decode(b64)


def _extract_gemini_image(resp_json: dict) -> bytes:
    """Pull the first ``image/*`` part out of a Gemini generateContent payload.

    Shared by the text-to-image and edit/compose nano-banana paths. Raises
    ``RuntimeError`` on no candidates, a text-only (refusal) response, or a
    response with no image part.
    """
    candidates = (resp_json.get("candidates") or [])
    if not candidates:
        raise RuntimeError(f"Gemini generateContent returned no candidates: {resp_json!r}")
    parts = (candidates[0].get("content") or {}).get("parts") or []
    for part in parts:
        inline = part.get("inline_data") or part.get("inlineData") or {}
        mime = inline.get("mime_type") or inline.get("mimeType") or ""
        data_b64 = inline.get("data")
        if isinstance(mime, str) and mime.startswith("image/") and data_b64:
            return base64.b64decode(data_b64)
    text_parts = [p.get("text") for p in parts if p.get("text")]
    if text_parts:
        raise RuntimeError(
            "Gemini nano-banana returned text instead of an image (likely a "
            f"refusal): {' '.join(text_parts)[:300]}"
        )
    raise RuntimeError(f"Gemini nano-banana response had no image part: {candidates[0]!r}")


def _image_nano_banana(cfg: dict, prompt: str) -> bytes:
    import httpx

    url = f"{GEMINI_BASE_URL}/{cfg['model']}:generateContent"
    body = {"contents": [{"parts": [{"text": prompt}]}]}
    with httpx.Client(timeout=cfg["timeout_seconds"]) as client:
        resp = client.post(url, params={"key": cfg["api_key"]}, json=body,
                           headers={"Content-Type": "application/json"})
    if resp.status_code >= 400:
        raise RuntimeError(f"Gemini generateContent returned {resp.status_code}: {_err_msg(resp)}")
    return _extract_gemini_image(resp.json())


# --------------------------------------------------------------------------- #
# Image edit / compose backends (image-conditioned generation)
# --------------------------------------------------------------------------- #
def _image_edit_openai(
    cfg: dict, prompt: str, size: str, quality: str, input_images: list[str]
) -> bytes:
    """gpt-image-2 edit/compose via multipart POST to /v1/images/edits.

    One ``image[]`` file part per input (order preserved: first = subject, later
    = background/reference). Returns decoded ``b64_json`` bytes. 4xx surfaces the
    provider message verbatim.
    """
    import httpx

    files = []
    for path in input_images:
        raw, mime, name = _load_input_image(path)
        files.append(("image[]", (name, raw, mime)))
    data = {"model": cfg["model"], "prompt": prompt, "size": size, "quality": quality, "n": "1"}
    headers = {"Authorization": f"Bearer {cfg['api_key']}"}  # httpx sets multipart Content-Type
    with httpx.Client(timeout=cfg["timeout_seconds"]) as client:
        resp = client.post(OPENAI_IMAGE_EDITS_URL, data=data, files=files, headers=headers)
    if resp.status_code >= 400:
        raise RuntimeError(f"OpenAI Images edit API returned {resp.status_code}: {_err_msg(resp)}")
    out = (resp.json().get("data") or [])
    if not out:
        raise RuntimeError(f"OpenAI Images edit API returned no data: {resp.json()!r}")
    b64 = out[0].get("b64_json")
    if not b64:
        raise RuntimeError("OpenAI Images edit response missing `b64_json`; check `model`.")
    return base64.b64decode(b64)


def _image_edit_nano_banana(cfg: dict, prompt: str, input_images: list[str]) -> bytes:
    """Gemini 2.5 Flash Image edit/compose via generateContent.

    Sends ``contents.parts = [{text: prompt}, {inline_data: {...}} per input]``
    and extracts the returned image via ``_extract_gemini_image`` (which also
    maps a text-only refusal to a RuntimeError).
    """
    import httpx

    parts: list[dict] = [{"text": prompt}]
    for path in input_images:
        raw, mime, _ = _load_input_image(path)
        parts.append({"inline_data": {"mime_type": mime, "data": base64.b64encode(raw).decode("ascii")}})
    url = f"{GEMINI_BASE_URL}/{cfg['model']}:generateContent"
    body = {"contents": [{"parts": parts}]}
    with httpx.Client(timeout=cfg["timeout_seconds"]) as client:
        resp = client.post(url, params={"key": cfg["api_key"]}, json=body,
                           headers={"Content-Type": "application/json"})
    if resp.status_code >= 400:
        raise RuntimeError(f"Gemini generateContent returned {resp.status_code}: {_err_msg(resp)}")
    return _extract_gemini_image(resp.json())


def generate_image(
    *, prompt: str, config_file: str = "", provider: str = "", model: str = "",
    api_key: str = "", output_dir: str = "", size: str = "", quality: str = "",
    input_images: list[str] | None = None,
) -> dict:
    if not isinstance(prompt, str) or not prompt.strip():
        raise RuntimeError("`prompt` is required and must be non-empty")
    cfg = load_config("image", config_file, {
        "provider": provider, "model": model, "api_key": api_key, "output_dir": output_dir,
    })
    provider = cfg["provider"]
    resolved_size = size or cfg["default_size"] or ("1:1" if provider == "gemini" else "1024x1024")
    resolved_quality = quality or cfg["default_quality"] or "auto"
    inputs = [p for p in (input_images or []) if isinstance(p, str) and p.strip()]

    if inputs:
        # Image-conditioned editing / compositing.
        if provider not in IMAGE_EDIT_PROVIDERS:
            raise RuntimeError(
                f"media image: provider {provider!r} does not support --input-image "
                f"editing; use --provider openai or nano-banana "
                f"(nano-banana is stronger for multi-image / background swaps).")
        if provider == "openai":
            if resolved_size not in OPENAI_SIZES:
                raise RuntimeError(
                    f"size {resolved_size!r} not supported by gpt-image-2; choose one of: {sorted(OPENAI_SIZES)}")
            if resolved_quality not in OPENAI_QUALITIES:
                raise RuntimeError(
                    f"quality {resolved_quality!r} not supported by gpt-image-2; choose one of: {sorted(OPENAI_QUALITIES)}")
            data = _image_edit_openai(cfg, prompt, resolved_size, resolved_quality, inputs)
        else:  # nano-banana
            data = _image_edit_nano_banana(cfg, prompt, inputs)
            resolved_size = resolved_size or "model-default"
            resolved_quality = "n/a"
        return _finalize(cfg, prompt, data, "png", {
            "mode": "edit", "size_used": resolved_size, "quality_used": resolved_quality,
            "input_images_used": inputs,
        })

    if provider == "openai":
        if resolved_size not in OPENAI_SIZES:
            raise RuntimeError(
                f"size {resolved_size!r} not supported by gpt-image-2; choose one of: {sorted(OPENAI_SIZES)}")
        if resolved_quality not in OPENAI_QUALITIES:
            raise RuntimeError(
                f"quality {resolved_quality!r} not supported by gpt-image-2; choose one of: {sorted(OPENAI_QUALITIES)}")
        data = _image_openai(cfg, prompt, resolved_size, resolved_quality)
    elif provider == "gemini":
        if resolved_size not in GEMINI_ASPECTS:
            raise RuntimeError(
                f"size {resolved_size!r} is not a valid Imagen aspect ratio; choose one of: {sorted(GEMINI_ASPECTS)}")
        data = _image_gemini(cfg, prompt, resolved_size)
        resolved_quality = "n/a"
    else:  # nano-banana
        data = _image_nano_banana(cfg, prompt)
        resolved_size = resolved_size or "model-default"
        resolved_quality = "n/a"

    return _finalize(cfg, prompt, data, "png",
                     {"mode": "generate", "size_used": resolved_size, "quality_used": resolved_quality})


# --------------------------------------------------------------------------- #
# Audio backends (text-to-speech)
# --------------------------------------------------------------------------- #
def _audio_openai(cfg: dict, prompt: str, voice: str, fmt: str) -> tuple[bytes, str]:
    import httpx

    fmt = fmt or "mp3"
    body = {"model": cfg["model"], "input": prompt, "voice": voice or "alloy", "response_format": fmt}
    headers = {"Authorization": f"Bearer {cfg['api_key']}", "Content-Type": "application/json"}
    with httpx.Client(timeout=cfg["timeout_seconds"]) as client:
        resp = client.post(OPENAI_SPEECH_URL, json=body, headers=headers)
    if resp.status_code >= 400:
        raise RuntimeError(f"OpenAI Speech API returned {resp.status_code}: {_err_msg(resp)}")
    return resp.content, fmt


def _audio_elevenlabs(cfg: dict, prompt: str, voice: str, fmt: str) -> tuple[bytes, str]:
    import httpx

    voice_id = voice or ELEVENLABS_DEFAULT_VOICE
    url = f"{ELEVENLABS_BASE}/{voice_id}"
    body = {"text": prompt, "model_id": cfg["model"]}
    headers = {"xi-api-key": cfg["api_key"], "Content-Type": "application/json"}
    with httpx.Client(timeout=cfg["timeout_seconds"]) as client:
        resp = client.post(url, params={"output_format": "mp3_44100_128"}, json=body, headers=headers)
    if resp.status_code >= 400:
        raise RuntimeError(f"ElevenLabs TTS API returned {resp.status_code}: {_err_msg(resp)}")
    return resp.content, "mp3"


def _audio_gemini(cfg: dict, prompt: str, voice: str) -> tuple[bytes, str]:
    import httpx

    url = f"{GEMINI_BASE_URL}/{cfg['model']}:generateContent"
    body = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {
            "responseModalities": ["AUDIO"],
            "speechConfig": {"voiceConfig": {"prebuiltVoiceConfig": {"voiceName": voice or "Kore"}}},
        },
    }
    with httpx.Client(timeout=cfg["timeout_seconds"]) as client:
        resp = client.post(url, params={"key": cfg["api_key"]}, json=body,
                           headers={"Content-Type": "application/json"})
    if resp.status_code >= 400:
        raise RuntimeError(f"Gemini TTS returned {resp.status_code}: {_err_msg(resp)}")
    candidates = (resp.json().get("candidates") or [])
    if not candidates:
        raise RuntimeError(f"Gemini TTS returned no candidates: {resp.json()!r}")
    parts = (candidates[0].get("content") or {}).get("parts") or []
    for part in parts:
        inline = part.get("inline_data") or part.get("inlineData") or {}
        mime = inline.get("mime_type") or inline.get("mimeType") or ""
        data_b64 = inline.get("data")
        if isinstance(mime, str) and mime.startswith("audio/") and data_b64:
            rate = 24000
            for tok in mime.split(";"):
                tok = tok.strip()
                if tok.startswith("rate="):
                    try:
                        rate = int(tok.split("=", 1)[1])
                    except ValueError:
                        pass
            return _pcm_to_wav(base64.b64decode(data_b64), rate), "wav"
    raise RuntimeError(f"Gemini TTS response had no audio part: {candidates[0]!r}")


def generate_audio(
    *, prompt: str, config_file: str = "", provider: str = "", model: str = "",
    api_key: str = "", output_dir: str = "", voice: str = "", audio_format: str = "",
) -> dict:
    if not isinstance(prompt, str) or not prompt.strip():
        raise RuntimeError("`prompt` is required and must be non-empty")
    cfg = load_config("audio", config_file, {
        "provider": provider, "model": model, "api_key": api_key, "output_dir": output_dir,
    })
    provider = cfg["provider"]
    resolved_voice = voice or cfg["voice"]
    resolved_fmt = audio_format or cfg["audio_format"]

    if provider == "openai":
        data, ext = _audio_openai(cfg, prompt, resolved_voice, resolved_fmt)
    elif provider == "elevenlabs":
        data, ext = _audio_elevenlabs(cfg, prompt, resolved_voice, resolved_fmt)
    else:  # gemini
        data, ext = _audio_gemini(cfg, prompt, resolved_voice)

    return _finalize(cfg, prompt, data, ext,
                     {"voice_used": resolved_voice or "default", "format_used": ext})


# --------------------------------------------------------------------------- #
# Video backends (async: submit → poll → download)
# --------------------------------------------------------------------------- #
def _video_replicate(cfg: dict, prompt: str, duration: str, aspect_ratio: str, input_image: str) -> tuple[bytes, str]:
    import httpx

    model = cfg["model"]
    if not model:
        raise RuntimeError(
            "video provider 'replicate' requires --model (an owner/name slug, "
            "e.g. 'google/veo-3', or a version id).")
    inp: dict[str, Any] = {"prompt": prompt}
    if duration:
        inp["duration"] = _maybe_number(duration)
    if aspect_ratio:
        inp["aspect_ratio"] = aspect_ratio
    if input_image:
        inp["image"] = _data_uri(input_image)

    headers = {"Authorization": f"Bearer {cfg['api_key']}", "Content-Type": "application/json"}
    if "/" in model and ":" not in model:
        url = f"{REPLICATE_BASE}/models/{model}/predictions"
        body: dict[str, Any] = {"input": inp}
    else:
        url = f"{REPLICATE_BASE}/predictions"
        body = {"version": model.split(":")[-1], "input": inp}

    with httpx.Client(timeout=cfg["timeout_seconds"]) as client:
        resp = client.post(url, json=body, headers=headers)
        if resp.status_code >= 400:
            raise RuntimeError(f"Replicate API returned {resp.status_code}: {_err_msg(resp)}")
        pred = resp.json()
        get_url = (pred.get("urls") or {}).get("get")
        status = pred.get("status")
        deadline = time.time() + cfg["timeout_seconds"]
        while status in ("starting", "processing") and get_url and time.time() < deadline:
            time.sleep(cfg["poll_interval_seconds"])
            pred = client.get(get_url, headers=headers).json()
            status = pred.get("status")
        if status != "succeeded":
            raise RuntimeError(f"Replicate prediction {status}: {pred.get('error') or pred!r}")
        output = pred.get("output")
        out_url = output[0] if isinstance(output, list) and output else output
        if not isinstance(out_url, str) or not out_url:
            raise RuntimeError(f"Replicate prediction had no output URL: {pred!r}")
        vid = client.get(out_url)
        if vid.status_code >= 400:
            raise RuntimeError(f"Replicate output download returned {vid.status_code}")
        return vid.content, _ext_from_url(out_url, "mp4")


def _dig_video_url(result: Any) -> str:
    """Best-effort extraction of a video URL from a fal result payload."""
    if isinstance(result, dict):
        vid = result.get("video")
        if isinstance(vid, dict) and isinstance(vid.get("url"), str):
            return vid["url"]
        for key in ("video_url", "url"):
            if isinstance(result.get(key), str):
                return result[key]
        videos = result.get("videos")
        if isinstance(videos, list) and videos and isinstance(videos[0], dict):
            if isinstance(videos[0].get("url"), str):
                return videos[0]["url"]
    raise RuntimeError(f"fal result had no recognizable video URL: {result!r}")


def _video_fal(cfg: dict, prompt: str, duration: str, aspect_ratio: str, input_image: str) -> tuple[bytes, str]:
    import httpx

    model = cfg["model"]
    if not model:
        raise RuntimeError(
            "video provider 'fal' requires --model (a fal-ai slug, e.g. "
            "'fal-ai/kling-video/v1/standard/text-to-video').")
    inp: dict[str, Any] = {"prompt": prompt}
    if duration:
        inp["duration"] = str(duration)
    if aspect_ratio:
        inp["aspect_ratio"] = aspect_ratio
    if input_image:
        inp["image_url"] = _data_uri(input_image)

    headers = {"Authorization": f"Key {cfg['api_key']}", "Content-Type": "application/json"}
    with httpx.Client(timeout=cfg["timeout_seconds"]) as client:
        resp = client.post(f"{FAL_QUEUE_BASE}/{model}", json=inp, headers=headers)
        if resp.status_code >= 400:
            raise RuntimeError(f"fal API returned {resp.status_code}: {_err_msg(resp)}")
        q = resp.json()
        status_url = q.get("status_url")
        response_url = q.get("response_url")
        status = q.get("status")
        deadline = time.time() + cfg["timeout_seconds"]
        while status not in ("COMPLETED", "ERROR", "FAILED") and status_url and time.time() < deadline:
            time.sleep(cfg["poll_interval_seconds"])
            status = client.get(status_url, headers=headers).json().get("status")
        if status != "COMPLETED":
            raise RuntimeError(f"fal request ended with status {status!r}")
        result = client.get(response_url, headers=headers).json()
        out_url = _dig_video_url(result)
        vid = client.get(out_url)
        if vid.status_code >= 400:
            raise RuntimeError(f"fal output download returned {vid.status_code}")
        return vid.content, _ext_from_url(out_url, "mp4")


def generate_video(
    *, prompt: str, config_file: str = "", provider: str = "", model: str = "",
    api_key: str = "", output_dir: str = "", duration: str = "",
    aspect_ratio: str = "", input_image: str = "",
) -> dict:
    if not isinstance(prompt, str) or not prompt.strip():
        raise RuntimeError("`prompt` is required and must be non-empty")
    cfg = load_config("video", config_file, {
        "provider": provider, "model": model, "api_key": api_key, "output_dir": output_dir,
    })
    provider = cfg["provider"]
    if provider == "replicate":
        data, ext = _video_replicate(cfg, prompt, duration, aspect_ratio, input_image)
    else:  # fal
        data, ext = _video_fal(cfg, prompt, duration, aspect_ratio, input_image)

    return _finalize(cfg, prompt, data, ext, {
        "duration_used": duration or "model-default",
        "aspect_ratio_used": aspect_ratio or "model-default",
    })
